on:
  push:
    branches: [postgres, ms-access]

jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./program/tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install -r ../requirements.txt
      - run: python tests.py